name: assignment3smarttracker
description: "A new Flutter project for the SmartTracker application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.24.2

  # API & Networking
  http: ^1.2.2

  # Formatting
  intl: ^0.19.0

  # GPS / LOCATION
  geolocator: ^13.0.1

  # CAMERA (Standard)
  camera: ^0.11.0+1
  # âœ… CAMERA WINDOWS (Yeh zaroori hai PC ke liye)
  camera_windows: ^0.2.1

  # MAPS FOR WINDOWS
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # LOCAL STORAGE
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true